### ISSUE TITLE
Implement Point Redemption

### ISSUE THREAD

**Issue by crscillitoe** [crscillitoe/RoboBanana#10]
Using some form of /redeem command, users should be prompted with a modal that contains a dropdown of all valid redemptions.

Upon redemption, a dialog should be sent to #stream-chat along the lines of "<USER> redeemed <REWARD>!" with interactable buttons attached to mark the reward as "Complete" or to "Refund" the points used to redeem the reward. These should only be interactable by Mods.

**Comment by braddotcoffee** [comment]
First part complete, commit can be found here: bd36799178cee2215c3110422bae51281ef77338

For users this includes:
1. A command for users to view their current point balance
2. A command for users to view the currently available rewards for them to redeem
3. A command for users to redeem a reward, subtracting the cost of the point balance from their total

For moderators, this also includes:
1. A command to create a new channel reward

**Comment by braddotcoffee** [comment]
Requirement clarification:
1. Upon redemption, a message should be sent to `#stream-chat` saying "@user redeemed <reward>!"
2. Embed view should then be opened in `#pending-rewards`. These should only be interactable by mods.

ADDITIONAL REQUIREMENT:
1. Upon completion/refund, a message should be sent back to `#stream-chat`
