### ISSUE TITLE
Implement Giveaway Tracking

### ISSUE THREAD

**Issue by teknogeek** [crscillitoe/RoboBanana#16]
We want to add giveaway tracking to the bot

- `/log_giveaway` will log a giveaway with a specified user, amount, and reason
- `/search_giveaway`  will let us see if a user has won a giveaway (optionally specify type, i.e. `emoji` or `funday friday`)

**Comment by EHSchutzman** [comment]
Optional: Have the bot assign an "emoji artist" role to users who are logged as giveaway winners for type `emoji`
