### ISSUE TITLE
In /mod payout_prediction we have indexing vs count from 1 issue

### ISSUE THREAD

**Issue by EHSchutzman** [crscillitoe/RoboBanana#21]
Prediction mentions options "One" and "Two" but payout requires an argument of 0 or 1.  Confusing bad CS creation, learn to count noobz.

**Comment by braddotcoffee** [comment]
The documentation specifies 0 or 1 right?

**Comment by EHSchutzman** [comment]
It does but visual for viewers specifies 1 or 2.  Confusing for mods running raffles that aren't christian
