### ISSUE TITLE
Create Discord events from Twitch schedule

### ISSUE THREAD

**Issue by teknogeek** [crscillitoe/RoboBanana#23]
![image](https://user-images.githubusercontent.com/2267004/201819284-604ab9cf-9caf-4ef1-a5a6-c3c8cd79388d.png)

Somethin like this

**Comment by MasonJF** [comment]
Would this be preferred as some kind of manual sync command, or perhaps a once daily cron that pulls the information from the twitch api and updates accordingly? @teknogeek
