### ISSUE TITLE
Hitting Max Connections for SQLAlchemy

### ISSUE THREAD

**Issue by braddotcoffee** [crscillitoe/RoboBanana#41]
Somehow the bot is hitting errors with maximum number of connections to the db.

![image](https://user-images.githubusercontent.com/17772186/209567946-552ffcf7-90cd-4fa4-95b5-e7ceb335a799.png)

Investigate if our `session()` pattern is
1) Creating a fresh connection every time (slow)
2) Failing to auto close (memory leak)

**Comment by braddotcoffee** [comment]
This is happening due to channel point accrual:
![image](https://user-images.githubusercontent.com/17772186/209568069-b7d8a535-41ca-4ad6-863d-2b72089c9470.png)

**Comment by teknogeek** [comment]
@braddotcoffee i believe we fixed this in #42, yeah?

**Comment by braddotcoffee** [comment]
Yes I believe we did - whoops!
