### ISSUE TITLE
Group good mornings by count

### ISSUE THREAD

**Issue by MasonJF** [crscillitoe/RoboBanana#51]
I suggest instead of having the bot display every users name with the full "Your count is..." we append all users to the string that is for that specific count, and put that one some kind of a  X number of user cycle with timeout.

By this I mean

```
Good morning @MasonJF! Your current weekly count is 2!
Good morning @Steppyx! Your current weekly count is 2!
Good morning @rüby! Your current weekly count is 2!
```
should become
```
Good morning
@MasonJF, @Steppyx, @rüby!
Your current weekly count is 2!
```

Then have this contain a maximum of say 20 users, or 60 seconds before it outputs.
This should cleanup the chat, and still achieve the goal of informing new users.

**Comment by crscillitoe** [comment]
resolved to use interactions API to avoid rate limit messages.
