### ISSUE TITLE
Good Morning Tier 2 Subs Raffle odds

### ISSUE THREAD

**Issue by EHSchutzman** [crscillitoe/RoboBanana#68]
Good Morning Tier 2 Subs (@Good Morning Tier 2) need to have tier 2 level raffle odds.

**Comment by teknogeek** [comment]
<img width="628" alt="image" src="https://user-images.githubusercontent.com/2267004/221427553-595309cf-e4c5-447e-8c05-b89de6b741e2.png">

done
