### ISSUE TITLE
Add `/mod chat_mode` command

### ISSUE THREAD

**Issue by teknogeek** [crscillitoe/RoboBanana#76]
We want to set up a command that lets us have #stream-chat go into a few different chat modes:

1. T3 chat mode (currently 3 different roles need send-message perm) + disable slowmode
2. Normal chat mode (all can chat, 15s slowmode)
3. T3 Jail mode (everyone BUT T3s can type, 15s slowmode)

ideally, there should be some dictionary at the top of the command that lets us easily add more down the line

**Comment by Foyerr** [comment]
Related 

Issue #45 Subscriber only chat toggle #60
