### ISSUE TITLE
Robonana temprole support bc Carl temproles suck

### ISSUE THREAD

**Issue by goodafterjun** [crscillitoe/RoboBanana#86]
- temprole add (adds specific temprole with customizable duration to specific user)
- temprole remove (removes specific temprole from specific user and nullifies existing timer/duration)
- temprole extend (adds X time to existing specific temprole for specific user)
- temprole status (check status/remaining time on all temproles for specific user)
- temprole mine (check status of all temproles for the user using the command)
- temproles view (view status of all temprole users of X role)

![image](https://github.com/crscillitoe/RoboBanana/assets/119389107/6e390983-4665-43b6-a718-7fda48964309)
^ Example of temprole add

**Comment by braddotcoffee** [comment]
Since we've had an influx of PRs recently, I wanna comment on here saying that I've taken care of all but `temprole view` functionality specified here. Will review #88
